version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

executors:
  default:
    docker:
      - image: cimg/node:18.20

commands:
  install-pnpm:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            node -p "require('os').homedir()" # Find the home directory
            echo 'export PATH="$PATH:/home/circleci/.node/corepack"' >> ~/.bashrc
            source ~/.bashrc
            corepack enable
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store
  install-dependencies:
    steps:
      - run:
          name: Install dependencies
          command: |
            pnpm install
            cd ./infrastructure && pnpm install
  cache-dependencies:
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
            - ./infrastructure/node_modules
  restore-dependencies:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  build-app:
    steps:
      - run: pnpm run build
  deploy-app:
    steps:
      - run: cd ./infrastructure && pnpm run deploy

jobs:
  build:
    executor: default
    resource_class: small
    steps:
      - checkout
      - install-pnpm
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - build-app
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - infrastructure/bin
  deploy:
    executor: aws-cli/default
    resource_class: small
    steps:
      - checkout
      - install-pnpm
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - deploy-app

workflows:
  version: 2
  ci-main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          context: aws-account
          requires:
            - build
          filters:
            branches:
              only:
                - main
