version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

executors:
  default:
    docker:
      - image: cimg/node:20.12.1

commands:
  install-dependencies:
    steps:
      - run:
          name: Install dependencies
          command: |
            pnpm install
            cd ./infrastructure && pnpm install
  cache-dependencies:
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
            - ./infrastructure/pnpm-store
  restore-dependencies:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  build-app:
    steps:
      - run:
          name: Build
          command: pnpm run build
      - run:
          name: Build CDK
          working_directory: ./infrastructure
          command: pnpm run build
  deploy-app:
    steps:
      - run:
          name: List build directory
          command: cd ./infrastructure && ls -la /home/circleci/project
      - run:
          name: Deploy
          command: cd ./infrastructure && pnpm run deploy

jobs:
  build:
    executor: default
    resource_class: small
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - build-app
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - build
            - infrastructure/bin
  deploy:
    executor: default
    resource_class: small
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - attach_workspace:
          at: .
      - aws-cli/setup
      - deploy-app

workflows:
  version: 2
  ci-main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          context: aws-account
          requires:
            - build
          filters:
            branches:
              only:
                - main
