version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

executors:
  default:
    docker:
      - image: cimg/node:20.12.1

commands:
  install-pnpm:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store
  install-dependencies:
    steps:
      - run:
          name: Clear npm cache
          command: npm cache clean --force
      - run:
          name: Install dependencies
          command: |
            pnpm install
            cd ./infrastructure && npm install
  cache-dependencies:
    steps:
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
            - ./infrastructure/node_modules
  restore-dependencies:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  build-app:
    steps:
      - run:
          name: Build
          command: pnpm run build::prod
      - run:
          name: Build CDK
          working_directory: ./infrastructure
          command: npm run build
  deploy-app:
    steps:
      - run:
          name: Deploy
          command: cd ./infrastructure && npm run deploy

jobs:
  build:
    executor: default
    resource_class: small
    steps:
      - checkout
      - install-pnpm
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - build-app
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - infrastructure/bin
  deploy:
    executor: default
    resource_class: small
    steps:
      - checkout
      - install-pnpm
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - deploy-app

workflows:
  version: 2
  ci-main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          context: aws-account
          requires:
            - build
          filters:
            branches:
              only:
                - main
